import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

# page configurations
st.set_page_config(page_title="Waste Management Analysis", layout="wide")

#loading the dataset
@st.cache_data
def load_data():
    data = pd.read_csv("cleaned_data.csv")
    return data

#creating functions
def plot_chart(data,country):
    filtered_data = data[data['Region'] == country]
    st.title(f"Waste Generated by {country}")
    chart_data = filtered_data[['Recycling', 'Energy Recovery', 'Landfill']].mean()
    st.bar_chart(chart_data)

#app
def main():
    st.title("Waste Management Analysis Dashboard")
    data = load_data()
    st.sidebar.title("Waste Management Analysis")
    country = st.sidebar.selectbox("Select a Country", data['Region'].unique())
    plot_chart(data, country)

if __name__ == "__main__":
    main()
