#%%
import pandas as pd
import matplotlib.pyplot as plt
#%%
#loading the dataset
df = pd.read_csv('raw_waste_management.csv')
print(df.head())
# %%
#pivoting the dataset to have the dimensions as columns and rows as the region by year
pivoted_df = df.pivot_table(index=['Geopolitical entity (reporting)', 'TIME_PERIOD'], columns='Waste management operations', values='OBS_VALUE').reset_index()
print(pivoted_df.head())
# %%
#renamming the columns
renamed_df = pivoted_df.rename(columns={'Geopolitical entity (reporting)': 'Region', 'TIME_PERIOD': 'Year','Disposal - incineration (D10)':'Disposal_Incineration', 'Disposal - incineration (D10) and recovery - energy recovery (R1)':'Energy Recovery','Disposal - landfill and other (D1-D7, D12)':'Landfill'})
print(renamed_df.head())
#%%
#checking for null values
print(renamed_df.isnull().sum())
#replacing null with 0 indicating no data recorded 
renamed_df.fillna(0, inplace=True)
#rechecking for null values
print(renamed_df.isnull().sum())
#%%
#checking for duplicates
print(renamed_df.duplicated().sum())
#%%
#checking data types
print(renamed_df.dtypes)
#%%
#dropping irrelavant column
renamed_df.drop(columns=['Disposal_Incineration'], inplace=True)
print(renamed_df.columns.to_list())

# %% --- Exploratory Data Analysis (EDA) ---
# Summary statistics
print(renamed_df.describe())

# %% --Univariate Analysis--
# Distribution of waste generated
plt.figure(figsize=(10, 6))
plt.hist(renamed_df['Waste generated'], bins=20, alpha=0.7)
plt.xlabel('Waste Generated')
plt.ylabel('Frequency')
plt.title('Distribution of Waste Generated')
plt.show()
# %% 
#counting the unique years
print(renamed_df['Year'].nunique())
# %% -- Bivariate Analysis --
#wasted generated by year
plt.figure(figsize=(12, 8)) 
plt.plot(renamed_df.groupby('Year')['Waste generated'].sum())
# %%
## %%
renamed_df.to_csv('cleaned_data.csv', index=False)
