import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

def plot_waste_generated_time(data_filtered):
    fig = px.line(data_filtered, x='Year', y='Waste generated', markers=True, title="Waste Generated Over Time")
    st.plotly_chart(fig, use_container_width=True)

def plot_donut(data_filtered):
    tot = data_filtered[['Recycling', 'Energy Recovery', 'Landfill']].sum()
    fig = px.pie(values=tot, names=tot.index, hole=0.5, title="Distribution of Waste Treatment Methods")
    st.plotly_chart(fig)

def plot_map(data):
    fig = px.choropleth(data, locations='Region', locationmode='country names', color='Waste generated', hover_name='Region', title="Total Waste Generated by Country")
    st.plotly_chart(fig)

def waste_treatment_time(data_filtered):
    fig, ax = plt.subplots()
    
    ax.plot(data_filtered['Year'], data_filtered['Recycling'], marker='o', label='Recycling')
    ax.plot(data_filtered['Year'], data_filtered['Energy Recovery'], marker='o', label='Energy Recovery')
    ax.plot(data_filtered['Year'], data_filtered['Landfill'], marker='o', label='Landfill')
    ax.set_title("Waste Treatment Methods Over Time")   
    ax.set_xlabel("Year")
    ax.set_ylabel("Amount of Waste")    
    ax.legend()
    st.pyplot(fig)

def recycle_rate(data_filtered, data):
    
    country_name = data_filtered['Region'].iloc[0]
    country_rate = (data_filtered['Recycling'] / data_filtered['Waste generated']).mean()
    
    rate_years = data_filtered['Year'].unique()
    eur_data = data[(data['Region'] == 'European Union - 27 countries (from 2020)') & (data['Year'].isin(rate_years))]
    eur_rate = (eur_data['Recycling'] / eur_data['Waste generated']).mean()
    
    df = pd.DataFrame({
        'Region': [country_name, 'Europe'],
        'Average Recycling Rate': [country_rate, eur_rate]
    })
    fig = px.bar(df, x='Region', y='Average Recycling Rate', color='Region',
        title=f"{country_name} VS European Union Recycle Rate"
    )
    st.plotly_chart(fig, use_container_width=True)
    