import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
orders = ['Recycling', 'Energy Recovery', 'Landfill']
colours = ["#21A06D", "#FFB300", "#0EB3C9"]
def plot_waste_generated_time(data_filtered):
    fig = px.line(data_filtered, x='Year', y='Waste generated', markers=True, title="Waste Generated Over Time")
    st.plotly_chart(fig, use_container_width=True)

def plot_donut(data_filtered):
    tot = data_filtered[['Recycling', 'Energy Recovery', 'Landfill']].sum()
    fig = px.pie(values=tot, names=tot.index, hole=0.5, title="Distribution of Waste Treatment Methods", color_discrete_sequence=colours,category_orders={"names": orders})
    st.plotly_chart(fig)

def plot_map(data,selected_country=None):
    fig = px.choropleth(data, 
                        locations='Region', 
                        locationmode='country names', 
                        color='Waste generated', 
                        hover_name='Region',
                        color_continuous_scale='Blues',
                        title="Total Waste Generated by Country")
#zooming in to europe and malta regions
    fig.update_geos(center={"lat": 50, "lon": 10}, projection_scale=3.5)
#adding a red pointer for the selected country
    if selected_country and selected_country != "All":
        highlight_df = data[data['Region'] == selected_country]
        
        fig.add_trace(go.Scattergeo(
            locations=highlight_df['Region'],
            locationmode='country names',
            marker=dict(size=10, color='red', line=dict(width=1, color='black')),
            name=f"{selected_country}"
        ))

    fig.update_layout(
        title="Waste Intensity by Country",
        margin={"r":0,"t":40,"l":0,"b":0}
    )
    st.plotly_chart(fig)

def waste_treatment_time(data_filtered):
    # Melt the data so Year is a column and Method/Amount are columns
    df_melted = data_filtered.melt(
        id_vars='Year', 
        value_vars=['Recycling', 'Energy Recovery', 'Landfill'],
        var_name='Method', 
        value_name='Amount')

    fig = px.line(df_melted, x='Year', y='Amount', color='Method', markers=True,title="Waste Treatment Methods Over Time",color_discrete_sequence=colours,category_orders={"Method": orders})
    st.plotly_chart(fig, use_container_width=True)

def recycle_rate(data_filtered, data):
    
    country_name = data_filtered['Region'].iloc[0]
    country_rate = (data_filtered['Recycling'] / data_filtered['Waste generated']).mean()
    
    rate_years = data_filtered['Year'].unique()
    eur_data = data[(data['Region'] == 'European Union - 27 countries (from 2020)') & (data['Year'].isin(rate_years))]
    eur_rate = (eur_data['Recycling'] / eur_data['Waste generated']).mean()
    
    df = pd.DataFrame({
        'Region': [country_name, 'Europe'],
        'Average Recycling Rate': [country_rate, eur_rate]
    })
    fig = px.bar(df, x='Region', y='Average Recycling Rate', color='Region',
        title=f"{country_name} VS European Union Recycle Rate")
    st.plotly_chart(fig, use_container_width=True)
    